import './globals.css'
import type { Metadata } from 'next'

import { NextAuthProvider } from "@/app/providers"
import { Inter } from 'next/font/google'

import Header from "@/app/components/Header"
import Footer from "@/app/components/Footer"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <NextAuthProvider>{children}</NextAuthProvider>
        <Footer />
      </body>
    </html>
  )
}
